apiVersion: v1
kind: Service
metadata:
  name: keval-wallets-service
spec:
  selector:
    app: keval-wallets
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
