apiVersion: v1
kind: Service
metadata:
  name: keval-marketplace-db-service
spec:
  selector:
    app: keval-marketplace-db
  type: ClusterIP
  ports:
    - protocol: TCP
      port: 9082
      targetPort: 9082
