apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: keval-marketplace-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: keval-marketplace-deployment
  minReplicas: 1
  maxReplicas: 3
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: Utilization
          # Scales up so that CPU utilization over all replicas is 50%
          averageUtilization: 50
    - type: Resource
      resource:
        name: memory
        target:
          type: Utilization
          # Scales up so that Memory utilization over all replicas is 70%
          averageUtilization: 70
  behavior:
    scaleUp:
      stabilizationWindowSeconds: 5
      policies:
        - type: Percent
          value: 50
          periodSeconds: 60
    scaleDown:
      stabilizationWindowSeconds: 10
      policies:
        - type: Percent
          value: 30
          periodSeconds: 60
