apiVersion: v1
kind: Service
metadata:
  name: keval-marketplace-service
spec:
  selector:
    app: keval-marketplace
  type: LoadBalancer
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
